const WEATHERS = {
  CLOUDY: "CLOUDS",
  CLOUDS: "CLOUDS",
  FOG: "FOG",
  SUNNY: "SUNNY",
  CLEAR: "CLEAR",
  RAIN: "RAIN",
  SNOW: "SNOW",
  DRIZZLE: "DROZZLE",
  THUNDERSTORM: "THUNDERSTORM",
  NIGHT_CLEAR: "NIGHT_CLEAR",
  HAZE: "HAZE",
  MIST: "MIST",
  SMOKE: "SMOKE",
};

export default WEATHERS;
