const WEATHERS = {
  CLOUDY: "CLOUDS",
  CLOUDS: "CLOUDS",
  FOG: "FOG",
  SUNNY: "SUNNY",
  CLEAR: "CLEAR",
  RAIN: "RAIN",
  SNOW: "SNOW",
  DRIZZLE: "DROZZLE",
  THUNDERSTORM: "THUNDERSTORM",
  NIGHT_CLEAR: "NIGHT_CLEAR",
  HAZE: "HAZE"
};

export default WEATHERS;
