const config = {
  ENVIRONMENT: process.env.REACT_APP_ENVIRONMENT,
  FIREBASE: {
    API_KEY: process.env.REACT_APP_FIREBASE_API_KEY,
    AUTH_DOMAIN: process.env.REACT_APP_FIREBASE_AUTH_DOMAIN,
    PROJECT_ID: process.env.REACT_APP_FIREBASE_PROJECT_ID,
    STORAGE_BUCKET: process.env.REACT_APP_FIREBASE_STORAGE_BUCKET,
    MESSAGING_SENDER_ID: process.env.REACT_APP_FIREBASE_MESSAGING_SENDER_ID,
    APP_ID: process.env.REACT_APP_FIREBASE_APP_ID,
  },
  OPEN_WEATHER_MAP: {
    API_BASE_URL: process.env.REACT_APP_OPEN_WEATHER_MAP_API_BASE_URL,
    API_KEY: process.env.REACT_APP_OPEN_WEATHER_MAP_API_KEY,
    DEFAULT_CITY: process.env.REACT_APP_OPEN_WEATHER_MAP_DEFAULT_CITY,
    VERSION: process.env.REACT_APP_OPEN_WEATHER_MAP_VERSION
  },
};

export default config;
