name: Deploy Firebase 🔥

on:
  push:
    branches:
      - develop
      - master

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: 
      name: staging
    strategy:
      matrix:
        node-version: [15.x]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install --production
    - name: Create .env
      run: |
        touch .env &&
        echo "ENVIRONMENT=${ENVIRONMENT}" > .env
        echo "FIREBASE_API_KEY=${FIREBASE_API_KEY}" >> .env
        echo "FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}" >> .env
        echo "FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}" >> .env
        echo "FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}" >> .env
        echo "FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}" >> .env
        echo "FIREBASE_APP_ID=${FIREBASE_APP_ID}" >> .env
        echo "OPEN_WEATHER_MAP_API_BASE_URL=${OPEN_WEATHER_MAP_API_BASE_URL}" >> .env
        echo "OPEN_WEATHER_MAP_API_KEY=${OPEN_WEATHER_MAP_API_KEY}" >> .env
        echo "OPEN_WEATHER_MAP_DEFAULT_CITY=${OPEN_WEATHER_MAP_DEFAULT_CITY}" >> .env
        echo "OPEN_WEATHER_MAP_VERSION=${OPEN_WEATHER_MAP_VERSION}" >> .env
      env:
        ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
        FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
        FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
        FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
        FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
        FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
        OPEN_WEATHER_MAP_API_BASE_URL: ${{secrets.OPEN_WEATHER_MAP_API_BASE_URL}}
        OPEN_WEATHER_MAP_API_KEY: ${{secrets.OPEN_WEATHER_MAP_API_KEY}}
        OPEN_WEATHER_MAP_DEFAULT_CITY: ${{secrets.OPEN_WEATHER_MAP_DEFAULT_CITY}}
        OPEN_WEATHER_MAP_VERSION: ${{secrets.OPEN_WEATHER_MAP_VERSION}}
    - name: Build Web Application 
      run: |
        npm run build:ci
    - name: Firebase Setup
      uses: pocket-apps/action-setup-firebase@v2
      with:
          firebase-token: ${{ secrets.FIREBASE_TOKEN }}
    - name: Firebase Deploy 🔥
      run: npm run firebase:deploy